/**
 * AI Client (Stub)
 * 
 * Interface and mock implementation for AI API calls.
 * Will be replaced with real implementations when backend is connected.
 */

import { StructuredPrompt, formatForAPI } from "./promptBuilder";

export interface GenerationResult {
  id: string;
  content: string;
  model: string;
  tokensUsed: {
    input: number;
    output: number;
  };
  duration: number; // ms
  cost: number; // USD
}

export interface GenerationError {
  code: string;
  message: string;
  retryable: boolean;
}

export interface AIClient {
  generate(prompt: StructuredPrompt): Promise<GenerationResult>;
  streamGenerate(
    prompt: StructuredPrompt,
    onChunk: (chunk: string) => void
  ): Promise<GenerationResult>;
  cancelGeneration(id: string): void;
}

/**
 * Mock AI Client for development/demo
 * 
 * Simulates generation with delays and placeholder responses.
 */
export class MockAIClient implements AIClient {
  private activeGenerations = new Map<string, boolean>();

  async generate(prompt: StructuredPrompt): Promise<GenerationResult> {
    const id = `gen-${Date.now()}`;
    const startTime = Date.now();
    
    // Simulate API delay
    await this.delay(1500 + Math.random() * 1000);

    const mockResponse = this.generateMockResponse(prompt);
    
    return {
      id,
      content: mockResponse,
      model: prompt.model.id,
      tokensUsed: {
        input: prompt.metadata.estimatedInputTokens,
        output: Math.ceil(mockResponse.length / 4),
      },
      duration: Date.now() - startTime,
      cost: 0, // Mock has no cost
    };
  }

  async streamGenerate(
    prompt: StructuredPrompt,
    onChunk: (chunk: string) => void
  ): Promise<GenerationResult> {
    const id = `gen-${Date.now()}`;
    const startTime = Date.now();
    this.activeGenerations.set(id, true);

    const mockResponse = this.generateMockResponse(prompt);
    const words = mockResponse.split(" ");

    // Stream words with delays
    for (let i = 0; i < words.length; i++) {
      if (!this.activeGenerations.get(id)) {
        break; // Cancelled
      }
      
      await this.delay(30 + Math.random() * 50);
      onChunk(words[i] + (i < words.length - 1 ? " " : ""));
    }

    this.activeGenerations.delete(id);

    return {
      id,
      content: mockResponse,
      model: prompt.model.id,
      tokensUsed: {
        input: prompt.metadata.estimatedInputTokens,
        output: Math.ceil(mockResponse.length / 4),
      },
      duration: Date.now() - startTime,
      cost: 0,
    };
  }

  cancelGeneration(id: string): void {
    this.activeGenerations.set(id, false);
  }

  private delay(ms: number): Promise<void> {
    return new Promise(resolve => setTimeout(resolve, ms));
  }

  private generateMockResponse(prompt: StructuredPrompt): string {
    const apiPayload = formatForAPI(prompt);
    
    // Extract app type from user prompt
    const userPrompt = prompt.userPrompt.toLowerCase();
    let appType = "application";
    
    if (userPrompt.includes("note")) appType = "note-taking app";
    else if (userPrompt.includes("track")) appType = "tracking app";
    else if (userPrompt.includes("budget")) appType = "budget app";
    else if (userPrompt.includes("weather")) appType = "weather app";
    else if (userPrompt.includes("recipe")) appType = "recipe app";
    else if (userPrompt.includes("todo") || userPrompt.includes("task")) appType = "task manager";

    const beliefNote = prompt.beliefContext
      ? `\n\nI've considered ${prompt.metadata.beliefCount} of your stored beliefs while planning this.`
      : "";

    return `# ${appType.charAt(0).toUpperCase() + appType.slice(1)} Plan

## Overview
Based on your request: "${prompt.userPrompt}"

I'll create a ${appType} with the following structure:

## Architecture
- **Framework**: React Native with Expo
- **State Management**: Zustand for simplicity
- **Storage**: AsyncStorage for local persistence
${prompt.metadata.backendEnabled ? "- **Backend**: Node.js with Express\n- **Database**: PostgreSQL" : ""}

## Key Features
1. Clean, intuitive user interface
2. Local data persistence
3. Responsive design for all screen sizes
${prompt.metadata.backendEnabled ? "4. Cloud sync capabilities\n5. User authentication" : ""}

## Next Steps
1. Generate the project structure
2. Create core components
3. Implement data layer
4. Add styling and animations
${beliefNote}

---
*Generated by ${prompt.model.name} (mock mode)*`;
  }
}

/**
 * Get the AI client instance
 * Currently returns mock client; will be configurable in future
 */
export function getAIClient(): AIClient {
  // TODO: Return real client based on environment/config
  return new MockAIClient();
}

